//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeApiTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationSchemas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationSchemas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokeApiTesting.Resources.ValidationSchemas", typeof(ValidationSchemas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;definitions&quot;: {},
        ///  &quot;$schema&quot;: &quot;http://json-schema.org/draft-07/schema#&quot;,
        ///  &quot;$id&quot;: &quot;https://jsonschema.net/&quot;,
        ///  &quot;type&quot;: &quot;object&quot;,
        ///  &quot;title&quot;: &quot;PokeAPI endpoint pagination Schema&quot;,
        ///  &quot;required&quot;: [
        ///    &quot;count&quot;,
        ///    &quot;next&quot;,
        ///    &quot;previous&quot;,
        ///    &quot;results&quot;
        ///  ],
        ///  &quot;properties&quot;: {
        ///    &quot;count&quot;: {
        ///      &quot;$id&quot;: &quot;#/properties/count&quot;,
        ///      &quot;type&quot;: &quot;integer&quot;,
        ///      &quot;title&quot;: &quot;The Count Schema&quot;,
        ///      &quot;default&quot;: 0,
        ///      &quot;examples&quot;: [
        ///        365
        ///      ],
        ///      &quot;pattern&quot;: &quot;([0-9]*)&quot;
        ///    },
        ///    &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string apiPaginationjSchemaString {
            get {
                return ResourceManager.GetString("apiPaginationjSchemaString", resourceCulture);
            }
        }
    }
}
